//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horario.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        public string Nomina { get; set; }
        public string NombreCarrera { get; set; }
        public string Siglas { get; set; }
    
        public virtual Dica Dica { get; set; }
    }
}
